# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Code It Right
email: theo@codeitright.co.za
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Theo Bohnen and this is my blog. I write about
  software development and whatever else catches my attention. I'm a learning
  butterfly going from one concept to another. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.codeitright.co.za" # the base hostname & protocol for your site
twitter_username: tbohnenjnr
github_username:  tbohnen

# Build settings
markdown: kramdown

theme: jekyll-theme-slate